### ISSUE TITLE
Device not published to HA

### ISSUE THREAD

**Issue by FWeinb** [wez/govee2mqtt#24]
Currently switching from govee_lan to govee2mqtt, thanks for providing this option as these govee lights are the worst behaving IoT devices I currently own. 

I am mainly interested in using the LAN only option as my Govee Lights won't be connected to the internet. Everything is working fine in the http govee controller provided by the docker container. (Would be great if there where an option to disable this)

I am using a standalone docker container via compose providing access to my IoT-VLAN. 
```yaml
  govee2mqtt:
    hostname: govee2mqtt
    container_name: govee2mqtt
    image: ghcr.io/wez/govee2mqtt:latest
    networks:
      proxy: # exposing this in my docker-only network 
      iot:
        ipv4_address: 10.2.1.8
    environment:
     - RUST_LOG=trace
     - GOVEE_LAN_NO_MULTICAST=true
     - GOVEE_LAN_BROADCAST_ALL=false
     - GOVEE_LAN_BROADCAST_GLOBAL=false
     - GOVEE_LAN_SCAN=10.2.1.255 # only scan IoT Network
     - GOVEE_MQTT_HOST=mosquitto 
     - GOVEE_MQTT_PORT=1883
     - GOVEE_MQTT_USER=${GOVEE_MQTT_USER}
     - GOVEE_MQTT_PASSWORD=${GOVEE_MQTT_PASSWORD}
    restart: unless-stopped
    depends_on:
      - mosquitto
  ```

I am using [Tag 2024.01.07-118ee247](https://github.com/wez/govee2mqtt/commit/c11a1687d051953049a9bdea114320e168454af2) you will find the trace-log attaced here:

```
govee2mqtt  | [2024-01-07T14:23:38Z TRACE govee::commands::serve] LAN disco: update and notify C9:18:C8:XX:XX:XX:XX:XX
govee2mqtt  | [2024-01-07T14:23:40Z INFO  govee::commands::serve] Devices returned from Govee's APIs
govee2mqtt  | [2024-01-07T14:23:40Z INFO  govee::commands::serve] H6076_5617 (C9:18:C8:XX:XX:XX:XX:XX) sku=H6076
govee2mqtt  | [2024-01-07T14:23:40Z INFO  govee::commands::serve]   LAN API: ip=10.2.1.59
govee2mqtt  | [2024-01-07T14:23:40Z INFO  govee::commands::serve] 
...
govee2mqtt  | [2024-01-07T14:27:06Z TRACE govee::service::hass] register_with_hass: mark as online
govee2mqtt  | [2024-01-07T14:27:06Z TRACE govee::service::hass] gv2mqtt/availability -> online
govee2mqtt  | [2024-01-07T14:27:06Z DEBUG mosquitto_rs::lowlevel] Client (null) sending PUBLISH (d0, q0, r0, m17, 'gv2mqtt/availability', ... (6 bytes))
govee2mqtt  | [2024-01-07T14:27:06Z TRACE govee::service::hass] register_with_hass: reporting state
govee2mqtt  | [2024-01-07T14:27:06Z TRACE govee::service::hass] gv2mqtt/sensor/global-version/state -> 2024.01.07-18bd57bc
govee2mqtt  | [2024-01-07T14:27:06Z DEBUG mosquitto_rs::lowlevel] Client (null) sending PUBLISH (d0, q0, r0, m18, 'gv2mqtt/sensor/global-version/state', ... (19 bytes))
govee2mqtt  | [2024-01-07T14:27:06Z TRACE govee::service::hass] register_with_hass: done
govee2mqtt  | [2024-01-07T14:27:38Z TRACE govee::lan_api] Send disco packet to 10.2.1.255
govee2mqtt  | [2024-01-07T14:27:38Z TRACE govee::lan_api] Send disco packet to 239.255.255.250
govee2mqtt  | [2024-01-07T14:27:38Z TRACE govee::lan_api] process_packet: addr=10.2.1.59:49159 data={"msg":{"cmd":"scan","data":{"ip":"10.2.1.59","device":"C9:18:C8:XX:XX:XX:XX:XX","sku":"H6076","bleVersionHard":"3.01.01","bleVersionSoft":"1.04.06","wifiVersionHard":"1.00.10","wifiVersionSoft":"1.02.11"}}}
govee2mqtt  | [2024-01-07T14:27:38Z TRACE govee::commands::serve] LAN disco: LanDevice { ip: 10.2.1.59, device: "C9:18:C8:XX:XX:XX:XX:XX", sku: "H6076", ble_version_hard: "3.01.01", ble_version_soft: "1.04.06", wifi_version_hard: "1.00.10", wifi_version_soft: "1.02.11" }
govee2mqtt  | [2024-01-07T14:27:38Z TRACE govee::lan_api] query status of 10.2.1.59
govee2mqtt  | [2024-01-07T14:27:38Z TRACE govee::lan_api] LanDevice::send_request to 10.2.1.59 DevStatus
govee2mqtt  | [2024-01-07T14:27:38Z TRACE govee::lan_api] process_packet: addr=10.2.1.59:49160 data={"msg":{"cmd":"scan","data":{"ip":"10.2.1.59","device":"C9:18:C8:XX:XX:XX:XX:XX","sku":"H6076","bleVersionHard":"3.01.01","bleVersionSoft":"1.04.06","wifiVersionHard":"1.00.10","wifiVersionSoft":"1.02.11"}}}
```
