### ISSUE TITLE
MQTT Custom Certificate Authority

### ISSUE THREAD

**Issue by jakeprice-me** [wez/govee2mqtt#257]
### Govee Device SKU

H61A0

### Govee2MQTT Version

latest

### Describe the issue

I'm running govee2mqtt as a standalone Docker container, and I'm running into the following issue.

```log
ha_govee2mqtt-01  | [2024-08-01T22:52:00 WARN  govee::commands::serve]   This device should be available via the LAN API, but didn't respond to probing yet. Possible causes:
ha_govee2mqtt-01  | [2024-08-01T22:52:00 WARN  govee::commands::serve]   1) LAN API needs to be enabled in the Govee Home App.
ha_govee2mqtt-01  | [2024-08-01T22:52:00 WARN  govee::commands::serve]   2) The device is offline.
ha_govee2mqtt-01  | [2024-08-01T22:52:00 WARN  govee::commands::serve]   3) A network configuration issue is preventing communication.
ha_govee2mqtt-01  | [2024-08-01T22:52:00 INFO  govee::commands::serve]
ha_govee2mqtt-01  | [2024-08-01T22:52:00 DEBUG mosquitto_rs::lowlevel] Client govee2mqtt/902649eb1e6647a0af40934517437402 sending CONNECT
ha_govee2mqtt-01  | [2024-08-01T22:52:00 ERROR mosquitto_rs::lowlevel] Error: Unrecognised command 16
ha_govee2mqtt-01  |
ha_govee2mqtt-01  | [2024-08-01T22:52:00 TRACE mosquitto_rs::client] client disconnected with reason=REASON code 2: Granted QoS 2
```

I think this is because my MQTT server uses MQTTS (like HTTPS) and a custom Certificate Authority. 

I've previously run into this issue with Zigbee2MQTT but Zigbee2MQTT provides a configuration option to provide a path to my certificate authority config as per below:

```yaml
mqtt:                                                                                                                                                                                                           
  server: mqtts://<domain>                                                                                                                                                                    
  user: <username>                                                                                                                                                                                                   
  password: <password>                                                                                                                                    
  ca: /app/data/certs/ca.crt  
```

Does govee2mqtt support such an option in the `.env` file, or is there another workaround?

Thanks

### Startup Diagnostics

ha_govee2mqtt-01  | [2024-08-01T22:51:48 INFO  govee::commands::serve] Starting service. version 2024.02.05-4c4fa0db
ha_govee2mqtt-01  | [2024-08-01T22:51:48 INFO  govee::commands::serve] Querying platform API for device list
ha_govee2mqtt-01  | [2024-08-01T22:51:48 INFO  govee::commands::serve] Querying undocumented API for device + room list
ha_govee2mqtt-01  | [2024-08-01T22:51:49 DEBUG mosquitto_rs::lowlevel] Client AP/5782254/fa9f386250854d3d9bde6a8840ec7f8e sending CONNECT
ha_govee2mqtt-01  | [2024-08-01T22:51:50 DEBUG mosquitto_rs::lowlevel] Client AP/5782254/fa9f386250854d3d9bde6a8840ec7f8e received CONNACK (0)
ha_govee2mqtt-01  | [2024-08-01T22:51:50 TRACE mosquitto_rs::client] connected: CONNACK code 0: Connection Accepted.
ha_govee2mqtt-01  | [2024-08-01T22:51:50 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
ha_govee2mqtt-01  | [2024-08-01T22:51:50 INFO  govee::commands::serve] Starting LAN discovery
ha_govee2mqtt-01  | [2024-08-01T22:51:50 INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
ha_govee2mqtt-01  | [2024-08-01T22:51:50 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
ha_govee2mqtt-01  | [2024-08-01T22:51:50 DEBUG mosquitto_rs::lowlevel] Client AP/5782254/fa9f386250854d3d9bde6a8840ec7f8e sending SUBSCRIBE (Mid: 1, Topic: GA/4f62ca32a07985a62b6ef959590fab3b, QoS: 0, Options: 0x00)
ha_govee2mqtt-01  | [2024-08-01T22:51:50 DEBUG mosquitto_rs::lowlevel] Client AP/5782254/fa9f386250854d3d9bde6a8840ec7f8e received SUBACK
ha_govee2mqtt-01  | [2024-08-01T22:52:00 INFO  govee::commands::serve] Devices returned from Govee's APIs
ha_govee2mqtt-01  | [2024-08-01T22:52:00 INFO  govee::commands::serve] Light Strip (30:07:D4:AD:FC:61:88:B1 H61A0)
ha_govee2mqtt-01  | [2024-08-01T22:52:00 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
ha_govee2mqtt-01  | [2024-08-01T22:52:00 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..18)
ha_govee2mqtt-01  | [2024-08-01T22:52:00 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false
ha_govee2mqtt-01  | [2024-08-01T22:52:00 INFO  govee::commands::serve]   Quirk { sku: "H61A0", icon: "mdi:led-strip-variant", supports_rgb: true, supports_brightness: true, color_temp_range: Some((2000, 9000)), avoid_platform_api: false, ble_only: false, lan_api_capable: true, device_type: Light, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true, show_as_preset_buttons: None }
ha_govee2mqtt-01  | [2024-08-01T22:52:00 WARN  govee::commands::serve]   This device should be available via the LAN API, but didn't respond to probing yet. Possible causes:
ha_govee2mqtt-01  | [2024-08-01T22:52:00 WARN  govee::commands::serve]   1) LAN API needs to be enabled in the Govee Home App.
ha_govee2mqtt-01  | [2024-08-01T22:52:00 WARN  govee::commands::serve]   2) The device is offline.
ha_govee2mqtt-01  | [2024-08-01T22:52:00 WARN  govee::commands::serve]   3) A network configuration issue is preventing communication.
ha_govee2mqtt-01  | [2024-08-01T22:52:00 INFO  govee::commands::serve]
ha_govee2mqtt-01  | [2024-08-01T22:52:00 DEBUG mosquitto_rs::lowlevel] Client govee2mqtt/902649eb1e6647a0af40934517437402 sending CONNECT
ha_govee2mqtt-01  | [2024-08-01T22:52:00 ERROR mosquitto_rs::lowlevel] Error: Unrecognised command 16
ha_govee2mqtt-01  |
ha_govee2mqtt-01  | [2024-08-01T22:52:00 TRACE mosquitto_rs::client] client disconnected with reason=REASON code 2: Granted QoS 2
ha_gove

### Additional Logs

_No response_

### Home Assistant Logs

_No response_

### Anything else?

_No response_
