### ISSUE TITLE
Devices not appearing in HomeAssistant MQTT integration

### ISSUE THREAD

**Issue by Everett115** [wez/govee2mqtt#276]
### Govee Device SKU

H6008

### Govee2MQTT Version

latest

### Describe the issue

I created the govee2mqtt docker container successfully, the logs show my devices in them and I don't see any errors. However the devices are not appearing in the HomeAssistant MQTT integration. The following are all my configurations:

**Docker Compose:**
```
mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/mosquitto/config:/mosquitto/config:rw
      - /opt/mosquitto/data:/mosquitto/data:rw
      - /opt/mosquitto/log:/mosquitto/log:rw
    ports:
      - 1883:1883
      - 9001:9001
  pv2mqtt:
    image: ghcr.io/wez/govee2mqtt:latest
    container_name: govee2mqtt
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host
    ports:
      - 4002:4002
```

**ENV File:**
```
GOVEE_EMAIL=MyEmail
GOVEE_PASSWORD=MYPassword
GOVEE_API_KEY=MyAPIKey
GOVEE_MQTT_HOST=192.168.1.69
GOVEE_MQTT_PORT=1883
GOVEE_MQTT_USER=MyMQTTUsername
GOVEE_MQTT_PASSWORD=MyMQTTPassword
GOVEE_TEMPERATURE_SCALE=F
RUST_LOG_STYLE=always
RUST_LOG=govee=trace
TZ=America/Chicago
```

**Home Assistant MQTT Integration Settings:**
```
Broker: 192.168.1.69
Port: 1883
Username: MyMQTTUsername
Password: MyMQTTPassword

MQTT Options:
Enable Discovery: true
Discovery Prefix: homeassistant
Enable Birth Message: true
Birth Message Topic: homeassistant/status
Birth message Payload: online
Birth Message QoS: 0
Birth Message Retain: false
Enable Will Message: true
Will Message Topic: homeassistant/status
Will Message Payload: offline
Will Message QoS: 0
Will Message Retain: False
```

### Startup Diagnostics

[2024-09-15T17:37:53 INFO  govee::commands::serve] 
[2024-09-15T17:37:57 TRACE govee::lan_api] Send disco packet to 239.255.255.250
[2024-09-15T17:37:58 INFO  govee::commands::serve] Starting service. version 2024.07.21-c9d27764
[2024-09-15T17:37:58 INFO  govee::commands::serve] Querying platform API for device list
[2024-09-15T17:37:58 TRACE govee::cache] cache hit for device-list
[2024-09-15T17:37:58 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-09-15T17:37:58 TRACE govee::cache] cache hit for account-info
[2024-09-15T17:37:58 TRACE govee::service::iot] LoginAccountResponse {
    a: REDACTED,
    b: REDACTED,
    account_id: REDACTED,
    client: REDACTED,
    is_savvy_user: false,
    refresh_token: Some(
        REDACTED,
    ),
    client_name: None,
    push_token: None,
    version_code: None,
    version_name: None,
    sys_version: None,
    token: REDACTED,
    token_expire_cycle: 57600,
    topic: REDACTED,
}
[2024-09-15T17:37:58 TRACE govee::cache] cache hit for iot-key
[2024-09-15T17:37:58 TRACE govee::service::iot] IotKey {
    endpoint: "aqm3wd1qlc3dy-ats.iot.us-east-1.amazonaws.com",
    log: "pro0",
    p12: REDACTED,
    p12_pass: REDACTED,
}
[2024-09-15T17:37:58 TRACE govee::service::iot] parsing IoT PFX key
[2024-09-15T17:37:58 TRACE govee::service::iot] Connecting to IoT aqm3wd1qlc3dy-ats.iot.us-east-1.amazonaws.com port 8883
[2024-09-15T17:37:58 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
[2024-09-15T17:37:58 INFO  govee::commands::serve] Starting LAN discovery
[2024-09-15T17:37:58 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
[2024-09-15T17:37:58 TRACE govee::lan_api] Send disco packet to 239.255.255.250
[2024-09-15T17:37:58 INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
