### ISSUE TITLE
H7160 Humidifier Water Level

### ISSUE THREAD

**Issue by davide169** [wez/govee2mqtt#79]
I have a H7160 humidifier.  So far everything is working but just curious if there would be a way to get a water level sensor?  It seems like it only reports if it is too low.  
Looking through the MQTT topics I do find this.
gv2mqtt/sensor/sensor-XXX-gv2mqtt-status/attributes
```
 - alarmType: 51
      eventState:
        options:
          - message: run out of Water
            name: lack
            value: 1
      instance: lackWaterEvent
      parameters: null
      type: devices.capabilities.event
```
