### ISSUE TITLE
Smart Humidifier Max night light can't be toggled on or color changed

### ISSUE THREAD

**Issue by fjrichman** [wez/govee2mqtt#89]
### Govee Device SKU

H7143

### Govee2MQTT Version

2024.01.18-4475eb63

### Describe the issue

In home assistant there is a "Night Light" bulb and it won't turn the night light on nor will it allow the night light to change colors.

Scenes work fine.

  ```
      {
            "sku": "H7143",
            "device": "",
            "deviceName": "Smart Humidifier",
            "type": "devices.types.humidifier",
            "capabilities": [
                {
                    "type": "devices.capabilities.on_off",
                    "instance": "powerSwitch",
                    "parameters": {
                        "dataType": "ENUM",
                        "options": [
                            {
                                "name": "on",
                                "value": 1
                            },
                            {
                                "name": "off",
                                "value": 0
                            }
                        ]
                    }
                },
                {
                    "type": "devices.capabilities.toggle",
                    "instance": "warmMistToggle",
                    "parameters": {
                        "dataType": "ENUM",
                        "options": [
                            {
                                "name": "on",
                                "value": 1
                            },
                            {
                                "name": "off",
                                "value": 0
                            }
                        ]
                    }
                },
                {
                    "type": "devices.capabilities.work_mode",
                    "instance": "workMode",
                    "parameters": {
                        "dataType": "STRUCT",
                        "fields": [
                            {
                                "fieldName": "workMode",
                                "dataType": "ENUM",
                                "options": [
                                    {
                                        "name": "Manual",
                                        "value": 1
                                    },
                                    {
                                        "name": "Auto",
                                        "value": 3
                                    }
                                ],
                                "required": true
                            },
                            {
                                "fieldName": "modeValue",
                                "dataType": "ENUM",
                                "options": [
                                    {
                                        "name": "Manual",
                                        "options": [
                                            {
                                                "value": 1
                                            },
                                            {
                                                "value": 2
                                            },
                                            {
                                                "value": 3
                                            },
                                            {
                                                "value": 4
                                            },
                                            {
                                                "value": 5
                                            },
                                            {
                                                "value": 6
                                            },
                                            {
                                                "value": 7
                                            },
                                            {
                                                "value": 8
                                            },
                                            {
                                                "value": 9
                                            }
                                        ]
                                    },
                                    {
                                        "defaultValue": 0,
                                        "name": "Auto"
                                    }
                                ],
                                "required": false
                            }
                        ]
                    }
                },
                {
                    "type": "devices.capabilities.range",
                    "instance": "humidity",
                    "parameters": {
                        "dataType": "INTEGER",
                        "range": {
                            "min": 40,
                            "max": 80,
                            "precision": 1
                        }
                    }
                },
                {
                    "type": "devices.capabilities.toggle",
                    "instance": "nightlightToggle",
                    "parameters": {
                        "dataType": "ENUM",
                        "options": [
                            {
                                "name": "on",
                                "value": 1
                            },
                            {
                                "name": "off",
                                "value": 0
                            }
                        ]
                    }
                },
                {
                    "type": "devices.capabilities.range",
                    "instance": "brightness",
                    "parameters": {
                        "dataType": "INTEGER",
                        "range": {
                            "min": 1,
                            "max": 100,
                            "precision": 1
                        }
                    }
                },
                {
                    "type": "devices.capabilities.color_setting",
                    "instance": "colorRgb",
                    "parameters": {
                        "dataType": "INTEGER",
                        "range": {
                            "min": 0,
                            "max": 16777215,
                            "precision": 1
                        }
                    }
                },
                {
                    "type": "devices.capabilities.mode",
                    "instance": "nightlightScene",
                    "parameters": {
                        "dataType": "ENUM",
                        "options": [
                            {
                                "name": "Forest",
                                "value": 1
                            },
                            {
                                "name": "Ocean",
                                "value": 2
                            },
                            {
                                "name": "Wetland",
                                "value": 3
                            },
                            {
                                "name": "Leisurely",
                                "value": 4
                            },
                            {
                                "name": "ASleep",
                                "value": 5
                            }
                        ]
                    }
                },
                {
                    "type": "devices.capabilities.event",
                    "instance": "lackWaterEvent",
                    "alarmType": 51,
                    "eventState": {
                        "options": [
                            {
                                "name": "lackWater",
                                "value": 1,
                                "message": "Lack of Water"
                            }
                        ]
                    }
                }
            ]
        }
```

### Startup Diagnostics

[2024-01-19T03:07:00Z INFO  govee::commands::serve] Starting service. version 2024.01.18-4475eb63

[2024-01-19T03:07:00Z INFO  govee::commands::serve] Querying platform API for device list

[2024-01-19T03:07:01Z INFO  govee::commands::serve] Querying undocumented API for device + room list

[2024-01-19T03:07:02Z INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.

[2024-01-19T03:07:02Z INFO  govee::commands::serve] Starting LAN discovery

[2024-01-19T03:07:02Z INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.

[2024-01-19T03:07:02Z INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery

[2024-01-19T03:07:12Z INFO  govee::commands::serve] Devices returned from Govee's APIs

[2024-01-19T03:07:12Z INFO  govee::commands::serve] Living Room Humidifier (* H7160)

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Platform API: devices.types.humidifier. supports_rgb=false supports_brightness=false

[2024-01-19T03:07:12Z INFO  govee::commands::serve]                 color_temp=None segment_rgb=None

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Undoc: room=Some("Living Room") supports_iot=true ble_only=false

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Quirk { sku: "H7160", icon: "mdi:air-humidifier", supports_rgb: true, supports_brightness: true, color_temp_range: None, avoid_platform_api: true, ble_only: false, lan_api_capable: false, device_type: Humidifier, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true, show_as_preset_buttons: None }

[2024-01-19T03:07:12Z INFO  govee::commands::serve] 

[2024-01-19T03:07:12Z INFO  govee::commands::serve] H5100_5841 (* H5100)

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Undoc: room=Some("Living Room") supports_iot=false ble_only=true

[2024-01-19T03:07:12Z WARN  govee::commands::serve]   Unknown device type. Cannot map to Home Assistant.

[2024-01-19T03:07:12Z INFO  govee::commands::serve] 

[2024-01-19T03:07:12Z INFO  govee::commands::serve] Smart Humidifier (* H7143)

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Platform API: devices.types.humidifier. supports_rgb=true supports_brightness=true

[2024-01-19T03:07:12Z INFO  govee::commands::serve]                 color_temp=None segment_rgb=None

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false

[2024-01-19T03:07:12Z INFO  govee::commands::serve] 

[2024-01-19T03:07:12Z INFO  govee::commands::serve] Bedroom Humidifier (* H7160)

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Platform API: devices.types.humidifier. supports_rgb=false supports_brightness=false

[2024-01-19T03:07:12Z INFO  govee::commands::serve]                 color_temp=None segment_rgb=None

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Undoc: room=Some("Bedroom") supports_iot=true ble_only=false

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Quirk { sku: "H7160", icon: "mdi:air-humidifier", supports_rgb: true, supports_brightness: true, color_temp_range: None, avoid_platform_api: true, ble_only: false, lan_api_capable: false, device_type: Humidifier, platform_temperature_sensor_units: None, platform_humidity_sensor_units: None, iot_api_supported: true, show_as_preset_buttons: None }

[2024-01-19T03:07:12Z INFO  govee::commands::serve] 

[2024-01-19T03:07:12Z INFO  govee::commands::serve] Mini Air Purifier (* H7120)

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Platform API: devices.types.air_purifier. supports_rgb=true supports_brightness=true

[2024-01-19T03:07:12Z INFO  govee::commands::serve]                 color_temp=None segment_rgb=None

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Undoc: room=Some("Bedroom") supports_iot=true ble_only=false

[2024-01-19T03:07:12Z INFO  govee::commands::serve] 

[2024-01-19T03:07:12Z INFO  govee::commands::serve] H5100_1570 (* H5100)

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Undoc: room=Some("Bedroom") supports_iot=false ble_only=true

[2024-01-19T03:07:12Z WARN  govee::commands::serve]   Unknown device type. Cannot map to Home Assistant.

[2024-01-19T03:07:12Z INFO  govee::commands::serve] 

[2024-01-19T03:07:12Z INFO  govee::commands::serve] Smart Dehumidifier Max (* H7151)

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Platform API: devices.types.dehumidifier. supports_rgb=false supports_brightness=false

[2024-01-19T03:07:12Z INFO  govee::commands::serve]                 color_temp=None segment_rgb=None

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=false

[2024-01-19T03:07:12Z INFO  govee::commands::serve] 

[2024-01-19T03:07:12Z INFO  govee::commands::serve] H5106_1A58 (* H5106)

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Undoc: room=Some("Bedroom") supports_iot=true ble_only=true

[2024-01-19T03:07:12Z WARN  govee::commands::serve]   Unknown device type. Cannot map to Home Assistant.

[2024-01-19T03:07:12Z INFO  govee::commands::serve] 

[2024-01-19T03:07:12Z INFO  govee::commands::serve] Big Air Purifier (* H7122)

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Platform API: devices.types.air_purifier. supports_rgb=false supports_brightness=false

[2024-01-19T03:07:12Z INFO  govee::commands::serve]                 color_temp=None segment_rgb=None

[2024-01-19T03:07:12Z INFO  govee::commands::serve]   Undoc: room=Some("Living Room") supports_iot=true ble_only=false

[2024-01-19T03:07:12Z INFO  govee::commands::serve] 

[2024-01-19T03:07:12Z INFO  govee::service::http] http server addr is 0.0.0.0:8056

### Additional Logs

[2024-01-19T03:04:53Z INFO  govee::service::hass] Command for Smart Humidifier (* H7143): {"state":"ON"}
[2024-01-19T03:04:53Z ERROR govee::service::hass] While dispatching Message { topic: "gv2mqtt/light/(deviceidwashere)/command", payload: "{\"state\":\"ON\"}", qos: AtMostOnce, retain: false, mid: 0 }: mqtt_light_command: state.device_power_on: don't know how to talk to humidifier Smart Humidifier (* H7143)

**Comment by wez** [comment]
Please share the metadata for your device:

* go to the device entry in for your device
* Find the entity id of the `Status` entity that is listed under your space heater and get its entity name. The default is probably something like `sensor.device_name_status`.

Then evaluate the following home assistant template by visiting `Developer Tools` | `Template`, replacing the entity name with what yours actually is:

```
{{
    {
      "meta": state_attr('sensor.device_name_status', 'platform_metadata'),
      "state": state_attr('sensor.device_name_status', 'platform_state'),
    }
}}
```

It should output a large-ish json blob, please share that here.

**Comment by wez** [comment]
scratch that; I couldn't see that you had already because the logs took up a lot of space on my screen

**Comment by wez** [comment]
This is a bit of a tricky area because Govee's metadata and platform API support around humidifiers is buggy.
As an example, we both have `H7160`, a device with a nightlight, but the platform API doesn't return any metadata for the nightlight. It is only possible to control its light via the IoT API.

At the moment the logic around the nightlight for humidifiers assumes that we have to use the IoT control because I haven't yet seen a device with non-broken metadata, at least, until now in your issue.

The other thing that is tricky is that the light control doesn't have a dedicated light-power-switch, there is only a whole-device power switch, and if we conflate the two, turning on the light will turn on the primary function of the device.  I have some logic in preparation that will try to deal with this by translating power control events into brightness control events.  I can't test this with my device because the platform API is broken for it and doesn't even think it has a light.

**Comment by wez** [comment]
Please try the latest version of the addon and let me know how you get on with it!

**Comment by fjrichman** [comment]
Controls work, state in Home Assistant doesn't update.

**Comment by wez** [comment]
Please share the device state by evaluating this template:

```
{{
      state_attr('sensor.device_name_status', 'platform_state')
}}
```

**Comment by fjrichman** [comment]
![Screenshot_20240119_094929_Home Assistant.jpg](https://github.com/wez/govee2mqtt/assets/5055387/e283373c-051c-4374-a32f-ce25680fec04)

**Comment by wez** [comment]
Please copy and paste the text; I often use this data in unit tests and I cannot do that with a screen shot where parts are cut off

**Comment by fjrichman** [comment]
platform_state:
  capabilities:
    - instance: online
      state:
        value: true
      type: devices.capabilities.online
    - instance: powerSwitch
      state:
        value: 0
      type: devices.capabilities.on_off
    - instance: warmMistToggle
      state:
        value: 1
      type: devices.capabilities.toggle
    - instance: workMode
      state:
        value:
          modeValue: 8
          workMode: 1
      type: devices.capabilities.work_mode
    - instance: humidity
      state:
        value: ""
      type: devices.capabilities.range
    - instance: nightlightToggle
      state:
        value: 0
      type: devices.capabilities.toggle
    - instance: brightness
      state:
        value: 100
      type: devices.capabilities.range
    - instance: colorRgb
      state:
        value: 16711722
      type: devices.capabilities.color_setting
    - instance: nightlightScene
      state:
        value: 5
      type: devices.capabilities.mode
  device: 21:E4:60:74:F4:5C:56:AC
  sku: H7143
friendly_name: Smart Humidifier Status

**Comment by wez** [comment]
Thanks; can you turn the nightlight on, capture that, then turn it off and capture it at that point too? I'm looking to see if we can get some state that correlates with the power state of the night light.  Maybe the `nightlightToggle`?  If that doesn't then I'm not sure that we can tell the light state with the data provided by the device.

**Comment by fjrichman** [comment]
On
```
platform_state:
  capabilities:
    - instance: online
      state:
        value: true
      type: devices.capabilities.online
    - instance: powerSwitch
      state:
        value: 0
      type: devices.capabilities.on_off
    - instance: warmMistToggle
      state:
        value: 1
      type: devices.capabilities.toggle
    - instance: workMode
      state:
        value:
          modeValue: 8
          workMode: 1
      type: devices.capabilities.work_mode
    - instance: humidity
      state:
        value: ""
      type: devices.capabilities.range
    - instance: nightlightToggle
      state:
        value: 1
      type: devices.capabilities.toggle
    - instance: brightness
      state:
        value: 100
      type: devices.capabilities.range
    - instance: colorRgb
      state:
        value: 16711722
      type: devices.capabilities.color_setting
    - instance: nightlightScene
      state:
        value: 5
      type: devices.capabilities.mode
  device: *
  sku: H7143
friendly_name: Smart Humidifier Status
```

Off
```
platform_state:
  capabilities:
    - instance: online
      state:
        value: true
      type: devices.capabilities.online
    - instance: powerSwitch
      state:
        value: 0
      type: devices.capabilities.on_off
    - instance: warmMistToggle
      state:
        value: 1
      type: devices.capabilities.toggle
    - instance: workMode
      state:
        value:
          modeValue: 8
          workMode: 1
      type: devices.capabilities.work_mode
    - instance: humidity
      state:
        value: ""
      type: devices.capabilities.range
    - instance: nightlightToggle
      state:
        value: 0
      type: devices.capabilities.toggle
    - instance: brightness
      state:
        value: 100
      type: devices.capabilities.range
    - instance: colorRgb
      state:
        value: 16711722
      type: devices.capabilities.color_setting
    - instance: nightlightScene
      state:
        value: 5
      type: devices.capabilities.mode
  device: *
  sku: H7143
friendly_name: Smart Humidifier Status
```
